//! SHA-1s of known-good copies of every system file Floppy's setup asks
//! for, so the missing-files list can say what Floppy is looking for by
//! content as well as by name. A user's copy is often stored under a name
//! no list could guess; a tool that has hashed the user's files can still
//! find it by one of these (cd.rs).
//!
//! **Generated by `scripts/update-known-hashes.py`. Don't edit by hand:**
//! change the script (its docstring lists the sources) and run it again.
//!
//! These are facts about files, not the files themselves (rule 3). Floppy
//! never relies on them: it still recognizes every file by its contents,
//! so a copy that isn't listed here still works when it's imported
//! directly.

/// A file's SHA-1, its size in bytes, and what it is.
pub struct KnownFile {
    pub sha1: &'static str,
    pub size: u64,
    pub label: &'static str,
}

/// Mac ROMs Basilisk II can use, from MAME. The ROM's own checksum is in brackets.
pub const MAC_ROMS: &[KnownFile] = &[
    KnownFile { sha1: "fd9e852e2d77fe17287ba678709b9334d4d74f1e", size: 1048576, label: "Color Classic (ECD99DC0)" },
    KnownFile { sha1: "9fba3d4f672a630745d65788b1d1119afa2c6728", size: 524288, label: "IIfx (4147DD77)" },
    KnownFile { sha1: "f923de4125aae810796527ff6e25364cf1d54eec", size: 524288, label: "IIsi (36B7FB6C)" },
    KnownFile { sha1: "560ce203d65178657ad09d03f532f86fa512bb40", size: 1048576, label: "IIvi/IIvx (4957EB49)" },
    KnownFile { sha1: "6bef5853ae736f3f06c2b4e79772f65910c3b7d4", size: 524288, label: "LC (350EACF0)" },
    KnownFile { sha1: "c54ee2f45020a4adeb7451adce04cd6e5fb69790", size: 1048576, label: "LC 520/550 (EDE66CBD)" },
    KnownFile { sha1: "f48a8adf06bce50beee033d0d814da0e5e916d08", size: 1048576, label: "LC 580, later (064DC91D)" },
    KnownFile { sha1: "c77df3220c861f37a2c553b6ee9241b202dfdffc", size: 1048576, label: "LC III (ECBBC41C)" },
    KnownFile { sha1: "74975c60d3a560fac9ad63125bb65a750fceaede", size: 1048576, label: "Macintosh TV (EAF1678D)" },
    KnownFile { sha1: "ef56fadc8adbe978f9d91fdf1543f66cb8468390", size: 1048576, label: "PowerBook 150 (FBA22562)" },
    KnownFile { sha1: "c0510682ae6d973652d7e17f3c3b27629c47afac", size: 1048576, label: "PowerBook 160/165c/180/180c (E33B2724)" },
    KnownFile { sha1: "ed1371c97117a5884da4a6605ecfc5abed48ae5a", size: 1048576, label: "PowerBook Duo 210/230 (ECFA989B)" },
    KnownFile { sha1: "be7bd9637203e4513b896146ddfc85c37817d131", size: 1048576, label: "PowerBook Duo 270c (0024D346)" },
    KnownFile { sha1: "d49dd69cf038784b8849793ad3c0e62c2d11f653", size: 1048576, label: "PowerBook Duo 280/280c (015621D7)" },
    KnownFile { sha1: "1d833125adf553a50f5994746c2c01aa5a1dbbf2", size: 1048576, label: "Quadra 605, LC 475 (FF7439EE)" },
    KnownFile { sha1: "f2a9ce387019bf272c6e3459d961b30f28942ac5", size: 1048576, label: "Quadra 610/650/800, Centris 610/650 (F1ACAD13)" },
    KnownFile { sha1: "47cd505b6a7c46e5c0ffa29f0d5037c83e94a02f", size: 1048576, label: "Quadra 630, LC 580 (06684214)" },
    KnownFile { sha1: "7a8ee468d16e64f2ad10cb8d1a45e6f07cc9e212", size: 1048576, label: "Quadra 700/900, PowerBook 140/170 (420DBFF3)" },
    KnownFile { sha1: "031f13bfd726a70cfe4c73c5967861bc77297a79", size: 1048576, label: "Quadra 800, Centris 610/650, earlier (F1A6F343)" },
    KnownFile { sha1: "d61dba4a2d2cf9048244b713eaa294100063658d", size: 1048576, label: "Quadra 950 (3DC27823)" },
];

/// Mac startup disks: installed System disks and bootable utility floppies,
/// from Internet Archive file metadata.
pub const MAC_BOOT_DISKS: &[KnownFile] = &[
    KnownFile { sha1: "774dda187048a681a50c927025a839b1eb8c3e30", size: 1474560, label: "Mac OS 7.6 Disk Tools (Utilities 1)" },
    KnownFile { sha1: "ed6df5d84dd400dbb572b614a53804ce06ed3220", size: 1474560, label: "Mac OS 7.6 Utilities 2" },
    KnownFile { sha1: "a008d47c43370882aa688a25ec4eedec6ce0e562", size: 10485760, label: "System 7.0.1, installed (10 MB)" },
    KnownFile { sha1: "da2239b83e572d7f594d1b7af050f5bc3f6fae84", size: 26214400, label: "System 7.5.3, installed (25 MB)" },
];

/// Kickstart ROMs, from FS-UAE's ROM table and TOSEC. Encrypted Amiga
/// Forever copies also need their rom.key.
pub const KICKSTARTS: &[KnownFile] = &[
    KnownFile { sha1: "00c15406beb4b8ab1a16aa66c05860e1a7c1ad79", size: 262144, label: "Kickstart v1.0 (A1000)(NTSC)" },
    KnownFile { sha1: "4192c505d130f446b2ada6bdc91dae730acafb4c", size: 262144, label: "Kickstart v1.1 (A1000)(NTSC)" },
    KnownFile { sha1: "16df8b5fd524c5a1c7584b2457ac15aff9e3ad6d", size: 262144, label: "Kickstart v1.1 (A1000)(PAL)" },
    KnownFile { sha1: "6a7bfb5dbd6b8f179f03da84d8d9528267b6273b", size: 262144, label: "Kickstart v1.2 (A1000)" },
    KnownFile { sha1: "11f9e62cf299f72184835b7b2a70a16333fc0d88", size: 262144, label: "Kickstart v1.2 (A500,A1000,A2000)" },
    KnownFile { sha1: "44ddfa642b0b2fa695b676cb6a876f37fb97c11c", size: 262144, label: "Kickstart v1.2 r33.180 (1986-10)(Commodore)(A500-A1000-A2000)[h HQC]" },
    KnownFile { sha1: "99246f6078ef937dfd4b3913ee041bda3d444232", size: 262144, label: "Kickstart v1.2 r33.180 (1986-10)(Commodore)(A500-A1000-A2000)[h Level42]" },
    KnownFile { sha1: "c39bd9094d4e5f4e28c1411f3086950406062e87", size: 262144, label: "Kickstart v1.3 (A3000)(SK)" },
    KnownFile { sha1: "891e9a547772fe0c6c19b610baf8bc4ea7fcb785", size: 262144, label: "Kickstart v1.3 (A500,A1000,A2000)" },
    KnownFile { sha1: "0547f2f8e024604e5f3a88b29320750ec128446b", size: 262155, label: "Kickstart v1.3 r34.005 (1987-12)(Commodore)(A3000)[encrypted, needs rom.key]" },
    KnownFile { sha1: "e4fbb13b2459757e5e1326c1fe9482155c4c7d60", size: 262144, label: "Kickstart v1.3 r34.005 (1987-12)(Commodore)(A3000)[h DC]" },
    KnownFile { sha1: "626b9cb424af96e477a178101030a88a34f36b46", size: 262144, label: "Kickstart v1.3 r34.005 (1987-12)(Commodore)(A3000)[h DC][a]" },
    KnownFile { sha1: "41754d876137c4c24f97a17e10ee949cba3cb5d3", size: 262144, label: "Kickstart v1.3 r34.005 (1987-12)(Commodore)(A3000)[h Galahad][ReloKick v1.4a]" },
    KnownFile { sha1: "671907e2cf5b08c1a51c8fb48e58afa766632d6d", size: 262144, label: "Kickstart v1.3 r34.005 (1987-12)(Commodore)(A3000)[h Geesus][ReloKick v1.41]" },
    KnownFile { sha1: "686b9320967956051215b46141c46799708143a6", size: 262144, label: "Kickstart v1.3 r34.005 (1987-12)(Commodore)(A3000)[h2][unknown hack]" },
    KnownFile { sha1: "754ad745ca232185df0867842fd1b3107d2588f5", size: 262144, label: "Kickstart v1.3 r34.005 (1987-12)(Commodore)(A3000)[h][unknown hack]" },
    KnownFile { sha1: "1ec9695989013d3e2f675ef321e7e95372e359bf", size: 262144, label: "Kickstart v1.3 r34.005 (1987-12)(Commodore)(A500-A1000-A2000-CDTV)[h Leonardo Fei][Guardian 1.2r]" },
    KnownFile { sha1: "f76316bf36dff14b20fa349ed02e4b11dd932b07", size: 524288, label: "Kickstart v1.4 (A3000)" },
    KnownFile { sha1: "5e470d0ca5c1e15f475886fd08a9bf207455312c", size: 524288, label: "Kickstart v2.0 r36.143 (1990-08)(Commodore)(A3000)[SuperKickstart]" },
    KnownFile { sha1: "f2cc0cc8bf9321df63456c439884c15cda0fe752", size: 524288, label: "Kickstart v2.02 r36.207 (1990-10)(Commodore)(A3000)[!][SuperKickstart]" },
    KnownFile { sha1: "d82ebb59afc53540ddf2d7187ecf239b7ea91590", size: 524288, label: "Kickstart v2.04 (A3000)" },
    KnownFile { sha1: "c5839f5cb98a7a8947065c3ed2f14f5f42e334a1", size: 524288, label: "Kickstart v2.04 (A500+)" },
    KnownFile { sha1: "47e8436ebf663a640860e6b4938068bf5b435cbf", size: 524288, label: "Kickstart v2.04 r37.175 (1991-05)(Commodore)(A2000)[developer]" },
    KnownFile { sha1: "c69c854190a41cff768b1e8ef25de97159a838c8", size: 524299, label: "Kickstart v2.04 r37.175 (1991-05)(Commodore)(A500+)[encrypted, needs rom.key]" },
    KnownFile { sha1: "87508de834dc7eb47359cede72d2e3c8a2e5d8db", size: 524288, label: "Kickstart v2.05 (A600)" },
    KnownFile { sha1: "02843c4253bbd29aba535b0aa3bd9a85034ecde4", size: 524288, label: "Kickstart v2.05 (A600HD)" },
    KnownFile { sha1: "f72d89148dac39c696e30b10859ebc859226637b", size: 524288, label: "Kickstart v2.05 (A600HD)" },
    KnownFile { sha1: "81159ef92a9a1834d14c20272edb74b7dc223507", size: 524288, label: "Kickstart v2.05 r37.210 (1991-11)(Commodore)[developer]" },
    KnownFile { sha1: "4f9c1a86f659d6e0958334d381297decb00f0322", size: 524288, label: "Kickstart v2.05 r37.210 (1991-11)(Commodore)[h][developer]" },
    KnownFile { sha1: "70033828182fffc7ed106e5373a8b89dda76faa5", size: 524288, label: "Kickstart v3.0 (A1200)" },
    KnownFile { sha1: "f0b4e9e29e12218c2d5bd7020e4e785297d91fd7", size: 524288, label: "Kickstart v3.0 (A4000)" },
    KnownFile { sha1: "17c01363393a6f66df771b969fc7eece145f3eeb", size: 524299, label: "Kickstart v3.0 r39.106 (1992-09)(Commodore)(A4000)[encrypted, needs rom.key]" },
    KnownFile { sha1: "a9494544511c6fe88b91fcab17f1b702f90c2d61", size: 524288, label: "Kickstart v3.0 r39.115 (1992)(Commodore)" },
    KnownFile { sha1: "e21545723fe8374e91342617604f1b3d703094f1", size: 524288, label: "Kickstart v3.1 (A1200)" },
    KnownFile { sha1: "f8e210d72b4c4853e0c9b85d223ba20e3d1b36ee", size: 524288, label: "Kickstart v3.1 (A3000)" },
    KnownFile { sha1: "5fe04842d04a489720f0f4bb0e46948199406f49", size: 524288, label: "Kickstart v3.1 (A4000)" },
    KnownFile { sha1: "81c631dd096bbb31d2af90299c76b774db74076c", size: 524288, label: "Kickstart v3.1 (A4000)" },
    KnownFile { sha1: "c3c481160866e60d085e436a24db3617ff60b5f9", size: 524288, label: "Kickstart v3.1 (A4000)(Cloanto)" },
    KnownFile { sha1: "b0ec8b84d6768321e01209f11e6248f2f5281a21", size: 524288, label: "Kickstart v3.1 (A4000T)" },
    KnownFile { sha1: "3b7f1493b27e212830f989f26ca76c02049f09ca", size: 524288, label: "Kickstart v3.1 (A500,A600,A2000)" },
    KnownFile { sha1: "3525be8887f79b5929e017b42380a79edfee542d", size: 524288, label: "Kickstart v3.1 r40.060 (1993-05)(Commodore)(CD32)[!]" },
    KnownFile { sha1: "29b1959de9200c14cc1af731516e76304f6cfb0a", size: 524288, label: "Kickstart v3.1 r40.062 (1993)(Commodore)(A600)[h]" },
    KnownFile { sha1: "24975ce0aed27cb88f707e889506fd155ac1f865", size: 524288, label: "Kickstart v3.1 r40.063 (1993-07)(Commodore)(A500-A600-A2000)[h ShapeShifter]" },
    KnownFile { sha1: "71806153213c9cf6bafedcc1bd5735e73b9e690d", size: 524288, label: "Kickstart v3.1 r40.068 (1993-12)(Commodore)(A1200)[f Harry Sintonen][h version number]" },
    KnownFile { sha1: "083f7cd3482f5b4cd13b43261bb8fc70e7b7ddca", size: 524288, label: "Kickstart v3.1 r40.068 (1993-12)(Commodore)(A1200)[h ShapeShifter]" },
    KnownFile { sha1: "06ab3a538b326ddc66cb0136f5de5e25a3b33920", size: 524299, label: "Kickstart v3.1 r40.068 (1993-12)(Commodore)(A4000)[encrypted, needs rom.key]" },
    KnownFile { sha1: "03e33f17cd451aab7ff4db1cdafb83f545a6abcf", size: 524288, label: "Kickstart v3.1 r40.068 (1993-12)(Commodore)(A4000)[h ShapeShifter]" },
    KnownFile { sha1: "6355a9ed5dc840422f9b73308a91be0d0bb506bd", size: 524288, label: "Kickstart v3.1.4-1 (A1200)" },
    KnownFile { sha1: "1a34b25a25e260e38e879172850143c80b461a64", size: 524288, label: "Kickstart v3.1.4-1 (A3000)" },
    KnownFile { sha1: "bad0ae388442db02eaeb6a5363ef43eb4e308ae6", size: 524288, label: "Kickstart v3.1.4-1 (A4000)" },
    KnownFile { sha1: "938a60a1d2c0d411f64bb27e5af40258b8decbf3", size: 524288, label: "Kickstart v3.1.4-1 (A4000T)" },
    KnownFile { sha1: "8a2405087ce182225656dd0b93069c45743f9e34", size: 524288, label: "Kickstart v3.1.4-1 (A500)" },
    KnownFile { sha1: "ef36c4638ee45de6bb93701761216c958cd0d57b", size: 524288, label: "Kickstart v3.1.4-2 (A1200)" },
    KnownFile { sha1: "d73ae3a36f12bb49bbf6ba04a890ff7aac419015", size: 524288, label: "Kickstart v3.1.4-2 (A3000)" },
    KnownFile { sha1: "aab44cd651e6b6f81a3effd8e0ba6b37ab322f32", size: 524288, label: "Kickstart v3.1.4-2 (A4000)" },
    KnownFile { sha1: "cd73aefe9cbfc258e7966cd14a7b2f4647c9ba45", size: 524288, label: "Kickstart v3.1.4-2 (A4000T)" },
    KnownFile { sha1: "d81cd6f131040895843d9dfa95a45bc95edd9704", size: 524288, label: "Kickstart v3.1.4-2 (A500)" },
    KnownFile { sha1: "5b2982876fec2166673be447643881262c84090e", size: 524288, label: "Kickstart v3.2 (A1200)" },
    KnownFile { sha1: "7bc0e75622d7254e11ea708e5d149007866c93ab", size: 524288, label: "Kickstart v3.2 (A3000)" },
    KnownFile { sha1: "37a8aa0b83782d75ce0b4a80631ff3459e91dc63", size: 524288, label: "Kickstart v3.2 (A4000)" },
    KnownFile { sha1: "ede1748eb2cbb1e86ac5bf7dc9b97246a4a54358", size: 524288, label: "Kickstart v3.2 (A4000T)" },
    KnownFile { sha1: "b88e364daf23c9c9920e548b0d3d944e65b1031d", size: 524288, label: "Kickstart v3.2 (A500/A600/A2000/A1000/CDTV)" },
    KnownFile { sha1: "7a9095f1107966f90267dc4cb3c1972efb4b78a8", size: 524288, label: "Kickstart v3.2 (Walker)" },
    KnownFile { sha1: "0984fc0df07dc0585db0923d580629f70fca420d", size: 524288, label: "Kickstart v3.2.1 (A1200)" },
    KnownFile { sha1: "eb93508f0bb0cde81d88bf22d05045565d66ef74", size: 524288, label: "Kickstart v3.2.1 (A3000)" },
    KnownFile { sha1: "7db3c3226acc0bfe548c788cf1bc7c4c8774d66f", size: 524288, label: "Kickstart v3.2.1 (A4000)" },
    KnownFile { sha1: "a75fcd349680cedeab06e496c6338394e81788d7", size: 524288, label: "Kickstart v3.2.1 (A4000T)" },
    KnownFile { sha1: "8f64ada68a7f128ba782e8dc9fa583344171590a", size: 524288, label: "Kickstart v3.2.1 (A500/A600/A2000/A1000/CDTV)" },
    KnownFile { sha1: "d9622547d84741b52c5472607f9aca75565cbba3", size: 524288, label: "Kickstart v3.2.2 (A1200)" },
    KnownFile { sha1: "443d98369aca3ba51ab2d4789d14fa9a26379c0b", size: 524288, label: "Kickstart v3.2.2 (A3000)" },
    KnownFile { sha1: "a3207bd5b5a3ca629010f3159ac793040fa813ef", size: 524288, label: "Kickstart v3.2.2 (A4000)" },
    KnownFile { sha1: "8e3fff2675cc1b97b4f072b63fd4de7093f7c627", size: 524288, label: "Kickstart v3.2.2 (A4000T)" },
    KnownFile { sha1: "7d5ebe686b69d59a863cc77a36b2cd60359a9ed2", size: 524288, label: "Kickstart v3.2.2 (A500/A600/A2000/A1000/CDTV)" },
    KnownFile { sha1: "3cbfc9e1fe396360157bd161de74fc901abee7ec", size: 524288, label: "Kickstart v3.X (A4000)(Cloanto)" },
];

/// Workbench boot disks, from TOSEC and the FS-UAE launcher.
pub const WORKBENCH_DISKS: &[KnownFile] = &[
    KnownFile { sha1: "8d853d46a9817161ba0a4f493ae6856d36e8d685", size: 901120, label: "Workbench v1.0 (1985)(Commodore)" },
    KnownFile { sha1: "76d622d544ee9df7ff59d55414e667cccf5a7878", size: 901120, label: "Workbench v1.0 (1985)(Commodore)[a]" },
    KnownFile { sha1: "c0aeffeca14022624a21255abf6e0ab1897d61bf", size: 901120, label: "Workbench v1.0 (1985)(Commodore)[Cloanto Amiga Forever Edition]" },
    KnownFile { sha1: "c7744937499cbf3d5469a870b00e53e0af1b512a", size: 901120, label: "Workbench v1.0 (1985)(Commodore)[m files moved]" },
    KnownFile { sha1: "112f4d8615134baa8a232241502b3bfef9a91916", size: 901120, label: "Workbench v1.0 (1985)(Commodore)[m files moved][a]" },
    KnownFile { sha1: "c7ea69ed5e85ec599165ab201619646c9b5729ba", size: 901120, label: "Workbench v1.0 (1985)(Commodore)[m startup-sequence][Cloanto Amiga Forever Edition]" },
    KnownFile { sha1: "3b8ccc24daa850fc1f0e927bf8511a974116b80a", size: 901120, label: "Workbench v1.1 rev 31.334 (1986)(Commodore)(DE)(Disk 1 of 2)(Workbench)" },
    KnownFile { sha1: "395c60b465185e9af02de9817ab17df53b7cbae1", size: 901120, label: "Workbench v1.1 rev 31.334 (1986)(Commodore)(Disk 1 of 2)(Workbench)[Cloanto Amiga Forever Edition]" },
    KnownFile { sha1: "e7e52e315f034b15083e8e4a14c630fea51cfbec", size: 901120, label: "Workbench v1.1 rev 31.334 (1986)(Commodore)(Disk 1 of 2)(Workbench)[m icon positions]" },
    KnownFile { sha1: "8c0cb7341064ac3e84396be889207573ec5fc380", size: 901120, label: "Workbench v1.1 rev 31.334 (1986)(Commodore)(Disk 1 of 2)(Workbench)[m system-configuration]" },
    KnownFile { sha1: "726f091c5ed60b7e9faaca375ca2ee63fb451666", size: 901120, label: "Workbench v1.2 rev 33.43 (1986)(Commodore)(A1000)(DE)(Disk 1 of 2)(Workbench)[m]" },
    KnownFile { sha1: "73f8dea3b56bb337a22d5c5f8b447df4f10a4fb0", size: 901120, label: "Workbench v1.2 rev 33.56 (1987)(Commodore)(A2000)(DE)(Disk 1 of 2)(Workbench)" },
    KnownFile { sha1: "850c68b878d6ef85a02e17b947e03fa26185879d", size: 901120, label: "Workbench v1.2 rev 33.56 (1987)(Commodore)(A2000)(Disk 1 of 2)(Workbench)[Cloanto Amiga Forever Edition]" },
    KnownFile { sha1: "bf8f1542aa525847e22bd3e913247848eb540da0", size: 901120, label: "Workbench v1.2 rev 33.56 (1987)(Commodore)(A500)(Disk 1 of 2)(Workbench)" },
    KnownFile { sha1: "ce2e2796b5b30f2e0cdf330225fad9b576541ea8", size: 901120, label: "Workbench v1.2 rev 33.56 (1987)(Commodore)(A500)(Disk 1 of 2)(Workbench)[m][v BGS9]" },
    KnownFile { sha1: "22c5809e3d5510ad821d190b544df6c3d04edddb", size: 901120, label: "Workbench v1.2 rev 33.56 (1987)(Commodore)(A500)(GB)(Disk 1 of 2)(Workbench)[m]" },
    KnownFile { sha1: "e56727bdb2de0e8ef5d3153d41929ddc03278035", size: 901120, label: "Workbench v1.2 rev 33.56 (1987)(Commodore)(A500-A2000)(Disk 1 of 2)(Workbench)[m]" },
    KnownFile { sha1: "53bb20a9afa2085df5d08d66cdcaa7aa92472870", size: 901120, label: "Workbench v1.2 rev 33.56 (1987)(Commodore)(Disk 1 of 2)(Workbench)[m]" },
    KnownFile { sha1: "04c280aebd78ce16ea40d7853799b953d6d079bc", size: 901120, label: "Workbench v1.3 rev 34.20 (1988)(Commodore)(A500-A2000)(Disk 1 of 2)(Workbench)[m]" },
    KnownFile { sha1: "d48769a027c3a156bcc11f9a04fadb5301407552", size: 901120, label: "Workbench v1.3 rev 34.20 (1988)(Commodore)(A500-A2000)(DK)(Disk 1 of 2)(Workbench)" },
    KnownFile { sha1: "44bace7520746691969d08f28dd68ef5ab2f15fb", size: 901120, label: "Workbench v1.3 rev 34.20 (1988)(Commodore)(A500-A2000)(GB)(Disk 1 of 2)(Workbench)" },
    KnownFile { sha1: "f9b05508d3ee04ac84d44f5c41d67ff4e842e6d7", size: 901120, label: "Workbench v1.3 rev 34.21 (1988)(Commodore)(A500-A2000)(NO)(Disk 1 of 2)(Workbench)" },
    KnownFile { sha1: "7c9d1b138c564c88f991e18951a9c8e710b6dc29", size: 901120, label: "Workbench v1.3.2 rev 34.28 (1989)(Commodore)(A500-A2000)(IT)(Disk 1 of 2)(Workbench)[m2]" },
    KnownFile { sha1: "04e2435c29b42b844785cf5da1d0ad58ab94dcdf", size: 901120, label: "Workbench v1.3.2 rev 34.28 (1989)(Commodore)(A500-A2000)(IT)(Disk 1 of 2)(Workbench)[m3]" },
    KnownFile { sha1: "7e9d8e4530418f400967a6294e17dfe2348e18c4", size: 901120, label: "Workbench v1.3.2 rev 34.28 (1989)(Commodore)(A500-A2000)(IT)(Disk 1 of 2)(Workbench)[m]" },
    KnownFile { sha1: "f1b61360f15e0d3a3637403f4e5ac77aee3343c1", size: 901120, label: "Workbench v1.3.2 rev 34.28 (1989)(Commodore)(A500-A2000)(NL)(Disk 1 of 2)(Workbench)[m]" },
    KnownFile { sha1: "cf802e9ce34e4de217a15d4c5f009329c4e3c51c", size: 901120, label: "Workbench v1.3.2 rev 34.28 (1989)(Commodore)(Disk 1 of 2)(Workbench)[m]" },
    KnownFile { sha1: "5aef0985c323271dbc35e4fb9c59721402dce0d1", size: 901120, label: "Workbench v1.3.2 rev 34.28 (1989)(Commodore)(GB)(Disk 1 of 2)(Workbench)[m2]" },
    KnownFile { sha1: "5283f44f9dd6b357f210ab30a69ddd6091a6bf70", size: 901120, label: "Workbench v1.3.2 rev 34.28 (1989)(Commodore)(GB)(Disk 1 of 2)(Workbench)[m3]" },
    KnownFile { sha1: "ebe243fbfab477792d28c1925ba20e0fd38836c3", size: 901120, label: "Workbench v1.3.2 rev 34.28 (1989)(Commodore)(GB)(Disk 1 of 2)(Workbench)[m]" },
    KnownFile { sha1: "a8d8e140c15b0ed9bfb6ab286dfae7ad5103d4e7", size: 901120, label: "Workbench v1.3.3 rev 34.34 (1990)(Commodore)(A500-A2000)(DE)(Disk 1 of 2)(Workbench)" },
    KnownFile { sha1: "07fafff9858fdbe425ef6e77798fec0b08da361f", size: 901120, label: "Workbench v1.3.3 rev 34.34 (1990)(Commodore)(A500-A2000)(DE)(Disk 1 of 2)(Workbench)[m]" },
    KnownFile { sha1: "86cb4e007f9fdcf6c5eda6adba3f60f188063875", size: 901120, label: "Workbench v1.3.3 rev 34.34 (1990)(Commodore)(A500-A2000)(Disk 1 of 2)(Workbench)" },
    KnownFile { sha1: "8d8314faa3b5fbc472c11d5fc669358522c1d00b", size: 901120, label: "Workbench v1.3.3 rev 34.34 (1990)(Commodore)(A500-A2000)(DK)(Disk 1 of 2)(Workbench)[m]" },
    KnownFile { sha1: "feba1a9f293311d5a22352adb68f11de97b1108c", size: 901120, label: "Workbench v1.3.3 rev 34.34 (1990)(Commodore)(Disk 1 of 2)(Workbench)[Cloanto Amiga Forever Edition]" },
    KnownFile { sha1: "e679ce219d67833c113dc224c78b077b95eec1ac", size: 901120, label: "Workbench v1.3.3 rev 34.34 (1990)(Commodore)(Disk 1 of 2)(Workbench)[m2]" },
    KnownFile { sha1: "32b382d516657aecbcbf218941fe1e5578bb29ba", size: 901120, label: "Workbench v1.3.3 rev 34.34 (1990)(Commodore)(Disk 1 of 2)(Workbench)[m3]" },
    KnownFile { sha1: "a4d4e5b7a4b7fcf4a7eb800aa3a62d236992f11b", size: 901120, label: "Workbench v1.3.3 rev 34.34 (1990)(Commodore)(Disk 1 of 2)(Workbench)[m]" },
    KnownFile { sha1: "d0c83e3169ae6fae11ccd5f21119c016bd64ad9b", size: 901120, label: "Workbench v1.4a15 rev 36.1 (1989)(Commodore)(alpha)[m]" },
    KnownFile { sha1: "20ff48e1dae1b4f7d616791e93e9612a488db110", size: 901120, label: "Workbench v1.4b1 rev 36.8 (1989)(Commodore)(beta)(Disk 1 of 4)(Workbench)" },
    KnownFile { sha1: "84d7f552b2729ec007f179a4e1251ff0971ba537", size: 901120, label: "Workbench v1.4b1 rev 36.8 (1989)(Commodore)(beta)(Disk 1 of 4)(Workbench)[m]" },
    KnownFile { sha1: "f8f9509aaaf10e99bd7c3694969af7f057648220", size: 901120, label: "Workbench v2.0 rev 36.68 (1990)(Commodore)(A3000)(Disk 1 of 3)(Workbench)[Cloanto Amiga Forever Edition]" },
    KnownFile { sha1: "8d5c0310a86f14fb3e6a1da001ceb50b9a592c51", size: 901120, label: "Workbench v2.04 rev 37.67 (1991)(Commodore)(Disk 1 of 4)(Workbench)" },
    KnownFile { sha1: "21a4363e236011f0173c393207a2225a0a3002b0", size: 901120, label: "Workbench v2.04 rev 37.67 (1991)(Commodore)(Disk 1 of 4)(Workbench)[a keymaps]" },
    KnownFile { sha1: "d9d8bc1964d9159b3669fadedcd140ead197b0b7", size: 901120, label: "Workbench v2.04 rev 37.67 (1991)(Commodore)(Disk 1 of 4)(Workbench)[a2 keymaps]" },
    KnownFile { sha1: "898c0c372c476d8410890388b81ca642cc0b381d", size: 901120, label: "Workbench v2.04 rev 37.67 (1991)(Commodore)(Disk 1 of 4)(Workbench)[h Cloanto]" },
    KnownFile { sha1: "5913fa0fb6cfa74ae9c80870f6ab8a4289036788", size: 901120, label: "Workbench v2.04 rev 37.67 (1991)(Commodore)(Disk 1 of 4)(Workbench)[h Cloanto][a disk label]" },
    KnownFile { sha1: "4d5c1830e04d1302fdad1eb85638104ab94fb353", size: 901120, label: "Workbench v2.05 rev 37.71 (1992)(Commodore)(Disk 1 of 4)(Workbench)" },
    KnownFile { sha1: "0931b08d8b9a02e0542f64689375d9af848d4ac2", size: 901120, label: "Workbench v2.05 rev 37.71 (1992)(Commodore)(Disk 1 of 4)(Workbench)[m bamcopy]" },
    KnownFile { sha1: "c20c96f6084fcbb312de95777ac77ca9aab0dc84", size: 901120, label: "Workbench v2.05 rev 37.71 (1992)(Commodore)(Disk 1 of 4)(Workbench)[m2]" },
    KnownFile { sha1: "6b3101885d3bddb6c8cecb4512ed6d7de3bbef25", size: 901120, label: "Workbench v2.05 rev 37.71 (1992)(Commodore)(Disk 1 of 4)(Workbench)[m3]" },
    KnownFile { sha1: "a29fcb30beaff175cd2c87ed7b0b5e14aa62b213", size: 901120, label: "Workbench v2.05 rev 37.71 (1992)(Commodore)(Disk 1 of 4)(Workbench)[m4]" },
    KnownFile { sha1: "8521b72ea596816a5b99bb01351a7b89483a8ebb", size: 901120, label: "Workbench v2.05 rev 37.71 (1992)(Commodore)(Disk 1 of 4)(Workbench)[m]" },
    KnownFile { sha1: "b96b01eeb750c7cd9b16e11c5ffc54224d537b36", size: 901120, label: "Workbench v2.1 rev 38.30 (1992)(Commodore)(M10)(Disk 2 of 5)(Workbench)[m]" },
    KnownFile { sha1: "5d4eefd81bf5d39c1fb352722ad5a022eefb7995", size: 901120, label: "Workbench v2.1 rev 38.35 (1992)(Commodore)(M10)(Disk 2 of 5)(Workbench)[Cloanto Amiga Forever Edition]" },
    KnownFile { sha1: "e6b571309593f248e3acddcdb42cd31f7cad9423", size: 901120, label: "Workbench v2.1 rev 38.35 (1992)(Commodore)(M10)(Disk 2 of 5)(Workbench)[m files added]" },
    KnownFile { sha1: "ec71fd594ccf61846ce699cf8011303514a25d19", size: 901120, label: "Workbench v2.1 rev 38.35 (1992)(Commodore)(M10)(Disk 2 of 5)(Workbench)[m gvpscsi]" },
    KnownFile { sha1: "ca3c52854d358dff1e78ea67a3bfaab157dc185c", size: 901120, label: "Workbench v2.1 rev 38.35 (1992)(Commodore)(M10)(Disk 2 of 5)(Workbench)[m gvpscsi][a]" },
    KnownFile { sha1: "160c22550635c98ffd9279db591dc4b0521fa54f", size: 901120, label: "Workbench v2.1 rev 38.35 (1992)(Commodore)(M10)(Disk 2 of 5)(Workbench)[m keymaps]" },
    KnownFile { sha1: "da8ab096d8d0807bcb766be78720c0c835715010", size: 901120, label: "Workbench v2.1 rev 38.35 (1992)(Commodore)(M10)(Disk 2 of 5)(Workbench)[m]" },
    KnownFile { sha1: "aefc903d0169cc0e1ec3f2c5ae3671cb0a5b36fa", size: 901120, label: "Workbench v2.1 rev 38.36 (1992)(Commodore)(M10)(Disk 2 of 5)(Workbench)" },
    KnownFile { sha1: "810b4314ff9a83299c22907fd681effcc493eec5", size: 901120, label: "Workbench v2.1 rev 38.36 (1992)(Commodore)(M10)(Disk 2 of 5)(Workbench)[m]" },
    KnownFile { sha1: "457abd6a286f8a3454530c67217ce1d9864f73af", size: 901120, label: "Workbench v3.0 rev 39.07 (1992)(Commodore)(beta)(Disk 2 of 6)(Workbench)[m startup-sequence]" },
    KnownFile { sha1: "e663c92a9c88fa38d02bbb299bea8ce70c56b417", size: 901120, label: "Workbench v3.0 rev 39.29 (1992)(Commodore)(A1200-A4000)(M10)(Disk 2 of 6)(Workbench)[!]" },
    KnownFile { sha1: "65ab988e597b456ac40320f88a502fc016d590aa", size: 901120, label: "Workbench v3.0 rev 39.29 (1992)(Commodore)(A1200-A4000)(M10)(Disk 2 of 6)(Workbench)[a]" },
    KnownFile { sha1: "9496daa66e6b2f4ddde4fa2580bb3983a25e3cd2", size: 901120, label: "Workbench v3.0 rev 39.29 (1992)(Commodore)(A1200-A4000)(M10)(Disk 2 of 6)(Workbench)[m bamcopy]" },
    KnownFile { sha1: "cf2f24cf5f5065479476a38ec8f1016b1f746884", size: 901120, label: "Workbench v3.0 rev 39.29 (1992)(Commodore)(A1200-A4000)(M10)(Disk 2 of 6)(Workbench)[m2]" },
    KnownFile { sha1: "0e7f30223af254df0e2b91ea409f35c56d6164a6", size: 901120, label: "Workbench v3.0 rev 39.29 (1992)(Commodore)(A1200-A4000)(M10)(Disk 2 of 6)(Workbench)[m3]" },
    KnownFile { sha1: "08c4afde7a67e6aaee1f07af96e95e9bed897947", size: 901120, label: "Workbench v3.0 rev 39.29 (1992)(Commodore)(A1200-A4000)(M10)(Disk 2 of 6)(Workbench)[m4]" },
    KnownFile { sha1: "4f4770caae5950eca4a2720e0424df052ced6a32", size: 901120, label: "Workbench v3.0 rev 39.29 (1992)(Commodore)(A1200-A4000)(M10)(Disk 2 of 6)(Workbench)[m5]" },
    KnownFile { sha1: "53086c3e44ec2d34e60ab65af71fb11941f4e0af", size: 901120, label: "Workbench v3.0 rev 39.29 (1992)(Commodore)(A1200-A4000)(M10)(Disk 2 of 6)(Workbench)[m]" },
    KnownFile { sha1: "486ea9520e60051c20ec01329d5a0fe3bb10b4fc", size: 901120, label: "Workbench v3.1 rev 40.42 (1994)(Commodore)(M10)(Disk 2 of 6)(Workbench)[!]" },
    KnownFile { sha1: "078f10ed06100573fa7bd39dd29cd482e2a35d09", size: 901120, label: "Workbench v3.1 rev 40.42 (1994)(Commodore)(M10)(Disk 2 of 6)(Workbench)[a2]" },
    KnownFile { sha1: "a67f8d46c033316f6a3e6c4e3c1b1fb3b19321b2", size: 901120, label: "Workbench v3.1 rev 40.42 (1994)(Commodore)(M10)(Disk 2 of 6)(Workbench)[a3]" },
    KnownFile { sha1: "ca5b96eaac70558273d3158f476a4e39ca8c7f75", size: 901120, label: "Workbench v3.1 rev 40.42 (1994)(Commodore)(M10)(Disk 2 of 6)(Workbench)[a]" },
    KnownFile { sha1: "05049a78b6574d2701f1b4560157f0c547910aeb", size: 901120, label: "Workbench v3.1 rev 40.42 (1994)(Commodore)(M10)(Disk 2 of 6)(Workbench)[m2]" },
    KnownFile { sha1: "54932a937a66994f522a29e03982137b1d2302e1", size: 901120, label: "Workbench v3.1 rev 40.42 (1994)(Commodore)(M10)(Disk 2 of 6)(Workbench)[m]" },
    KnownFile { sha1: "2ad1ebb52c73981ba19625dc8a1c8132568d36d8", size: 901120, label: "Workbench v3.1 rev 40.42 (1996)(ESCOM)(M10)(Disk 2 of 6)(Workbench)" },
    KnownFile { sha1: "8c24a929fb029b19d697629997bfb154f5663a17", size: 901120, label: "Workbench v3.1 rev 40.42 (1996)(ESCOM)(M10)(Disk 2 of 6)(Workbench)[m files deleted]" },
    KnownFile { sha1: "e3d6a346bc8071e0d9445298672dfe0eeeac0115", size: 901120, label: "Workbench v3.1 rev 40.42 (1996)(ESCOM)(M10)(Disk 2 of 6)(Workbench)[m2]" },
    KnownFile { sha1: "f864a13e0b7c610f852a74bd9871ae81678f7d45", size: 901120, label: "Workbench v3.1 rev 40.42 (1996)(ESCOM)(M10)(Disk 2 of 6)(Workbench)[m3]" },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tables_are_well_formed() {
        let mut seen = std::collections::HashSet::new();
        let tables: [(&[KnownFile], fn(u64) -> bool); 4] = [
            (MAC_ROMS, |s| matches!(s, 524_288 | 1_048_576)),
            (MAC_BOOT_DISKS, |s| s >= 400 * 1024),
            // Plain dumps, and Amiga Forever's encrypted ones (11-byte header).
            (KICKSTARTS, |s| matches!(s, 262_144 | 524_288 | 262_155 | 524_299)),
            (WORKBENCH_DISKS, |s| s == 901_120),
        ];
        for (table, size_ok) in tables {
            assert!(!table.is_empty());
            for f in table {
                assert!(f.sha1.len() == 40 && f.sha1.bytes().all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b)), "{}", f.sha1);
                assert!(size_ok(f.size), "{} {}", f.label, f.size);
                assert!(!f.label.is_empty() && !f.label.contains(['\n', '\t']));
                assert!(seen.insert(f.sha1), "duplicate {}", f.sha1);
            }
        }
    }
}
